### ISSUE TITLE
Fix mobile view

### ISSUE THREAD

**Issue by dskunkler** [dskunkler/climbing-journal#22]
Add tailwind stuff to make it work on Mobile. Currently weekview overflows

**Comment by bmclachlin1** [comment]
Is this issue still relevant? Seems to look fine on IPhone SE

![Screenshot (161)](https://github.com/dskunkler/climbing-journal/assets/36721162/f57380b6-c085-49d1-b2bd-2feaf17754bd)

**Comment by dskunkler** [comment]
Yea if you select a date it overflows
![5963D41D-7762-402E-8A8A-2754E3ED106E](https://github.com/dskunkler/climbing-journal/assets/25286027/b93dfef2-37d7-4bdc-9374-53927dcf13c8)
