### ISSUE TITLE
Center calendar

### ISSUE THREAD

**Issue by dskunkler** [dskunkler/climbing-journal#8]

**Comment by shirsho-roy** [comment]
I would like to work on this issue. Could you assign it me?

**Comment by dskunkler** [comment]
Assigned to you @shirsho-roy . I've been using tailwind, here's some documentation that might help https://tailwindcss.com/docs/justify-content

Also, I have clerk secrets in my .env to enable the auth. You might need to generate and add those to your .env to have it work locally, I'm not positive. Please let me know if you have any troubles, or if it doesn't work and you did something to fix it and I'll update the readme to include those steps.

**Comment by shirsho-roy** [comment]
@dskunkler  Sure I will look to this.

**Comment by shirsho-roy** [comment]
@dskunkler I am getting some issue in database url in the .env file. Could you help me with it?

**Comment by shirsho-roy** [comment]
No worries though, I fixed the css issue. Sent Pull Request.

**Comment by dskunkler** [comment]
Thank you
